baseURL = "https://mybrainhertz.co.uk/"
languageCode = "en-us"
title = "Well lets take a look at it, Mr Gumby!"

pygmentsCodefences = true
pygmentsUseClasses = false
pygmentsStyle = 'friendly' #required for lexer to work

# googleAnalytics = "UA-177014444-1"
googleAnalytics = "G-8PKWFQVGKH"
disqusShortname = 'www-mybrainhertz-co-uk'

[markup]
[markup.goldmark.renderer]
unsafe = true


[permalinks]
  electronics = "/:filename/"
  food = "/:filename/"
  misc = "/:filename/"
  photography = "/:filename/"
  plants = "/:filename/"


[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Electronics"
    pre = "cpu"
    url = "/electronics/"
    weight = 2

  [[menu.main]]
    name = "Food"
    pre = "heart"
    url = "/food/"
    weight = 3
    type = "food"
    
  [[menu.main]]
    name = "Photography"
    pre = "aperture"
    url = "/photography/"
    weight = 4   

  [[menu.main]]
    name = "Misc"
    pre = "coffee"
    url = "/misc/"
    weight = 5    

  [[menu.main]]
    name = "Greenhouse"
    pre = "sun"
    url = "/Greenhouse/"
    weight = 6


#  [[menu.main]]
#    name = "Tags"
#    pre = "tag"
#    url = "/tags/"
#    weight = 7

  [[menu.main]]
  identifier = "archive"
  name = "Archive"
  pre="archive"
  url = "/archive/"
  weight = 8


[taxonomies]
  tag = "tags"

[params]
  dateFormat = "Jan 2, 2006"
  homeText = "J. Spencer"


